/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;

/**
 *
 * @author maxid
 */
public class VistaVentas extends javax.swing.JInternalFrame {

    /**
     * Creates new form VistaVentas
     */
    public VistaVentas() {
        initComponents();
        cargarColumnas1();
        cargarColumnas2();
         ((javax.swing.plaf.basic.BasicInternalFrameUI) this.getUI()).setNorthPane(null);
    }
    
    public void cargarColumnas1(){
         modeloTablaProductosArriba.addColumn("Id");
         modeloTablaProductosArriba.addColumn("Descripción");
        modeloTablaProductosArriba.addColumn("Stock");
        modeloTablaProductosArriba.addColumn("Proveedor");
         
        TableColumn ColId= tablaArriba.getColumn("Id");
        TableColumn ColNombre = tablaArriba.getColumn("Descripción");
        TableColumn colStock = tablaArriba.getColumn("Stock");
        TableColumn colNomProveedor = tablaArriba.getColumn("Proveedor");
        
        ColId.setMaxWidth(30);
        ColId.setMinWidth(0);

        ColNombre.setMaxWidth(365);
        ColNombre.setMinWidth(10);

        colStock.setMinWidth(105);
        colStock.setMaxWidth(80);

        colNomProveedor.setMaxWidth(250);
        colNomProveedor.setMinWidth(50);

    }
    
    public void cargarColumnas2(){
         modeloTablaProductosAbajo.addColumn("Id");
        modeloTablaProductosAbajo.addColumn("Cantidad");
         modeloTablaProductosAbajo.addColumn("Descripción");
        modeloTablaProductosAbajo.addColumn("Stock");
        modeloTablaProductosAbajo.addColumn("Proveedor");
        
        TableColumn ColId = tablaAbajo.getColumn("Id"); 
         TableColumn ColCantidad = tablaAbajo.getColumn("Cantidad");
        TableColumn ColNombre = tablaAbajo.getColumn("Descripción");
        TableColumn colStock = tablaAbajo.getColumn("Stock");
        TableColumn colNomProveedor = tablaAbajo.getColumn("Proveedor");
        
        ColId.setMaxWidth(30);
        ColId.setMinWidth(0);
        
        ColCantidad.setMaxWidth(70);
        ColCantidad.setMinWidth(0);

        ColNombre.setMaxWidth(335);
        ColNombre.setMinWidth(10);

        colStock.setMinWidth(45);
        colStock.setMaxWidth(80);

        colNomProveedor.setMaxWidth(250);
        colNomProveedor.setMinWidth(50);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaArriba = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        txtDesc = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtCantidad = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaAbajo = new javax.swing.JTable();
        btnAnadir = new javax.swing.JButton();
        btnQuitarProd = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnAceptar = new javax.swing.JButton();

        setBorder(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI Semilight", 1, 14)); // NOI18N
        jLabel1.setText("Venta");

        tablaArriba.setModel(modeloTablaProductosArriba);
        jScrollPane1.setViewportView(tablaArriba);

        jLabel2.setText("Descripción");

        jLabel3.setText("Cantidad");

        tablaAbajo.setModel(modeloTablaProductosAbajo);
        jScrollPane2.setViewportView(tablaAbajo);

        btnAnadir.setText("Añadir");

        btnQuitarProd.setText("Quitar producto");

        btnCancelar.setText("Eliminar venta");

        btnAceptar.setText("Restar stock");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(jScrollPane2)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDesc, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnAnadir, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(341, 341, 341)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnQuitarProd, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(12, 12, 12)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(btnAnadir)
                    .addComponent(txtDesc)
                    .addComponent(txtCantidad))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnQuitarProd, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(60, 60, 60))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnAceptar;
    public javax.swing.JButton btnAnadir;
    public javax.swing.JButton btnCancelar;
    public javax.swing.JButton btnQuitarProd;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JTable tablaAbajo;
    public javax.swing.JTable tablaArriba;
    public javax.swing.JTextField txtCantidad;
    public javax.swing.JTextField txtDesc;
    // End of variables declaration//GEN-END:variables
    public DefaultTableModel modeloTablaProductosArriba = new DefaultTableModel();
    public DefaultTableModel modeloTablaProductosAbajo = new DefaultTableModel();
}
