/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;

/**
 *
 * @author maxid
 */
public class VistaListaRecepcionPedido extends javax.swing.JInternalFrame {

    /**
     * Creates new form VistaListaRecepcionPedido
     */
    public VistaListaRecepcionPedido() {
        initComponents();
         ((javax.swing.plaf.basic.BasicInternalFrameUI) this.getUI()).setNorthPane(null);
         cargarColumnas();
    }
    
     public void cargarColumnas(){
        
         modeloTablaRecepcionPedido.addColumn("Cantidad");       
        modeloTablaRecepcionPedido.addColumn("Descripción");
        modeloTablaRecepcionPedido.addColumn("Proveedor");
         
       
        TableColumn ColCantidad = tablaListaRecepcionPedido.getColumn("Cantidad");        
        TableColumn colDescripcion = tablaListaRecepcionPedido.getColumn("Descripción");
        TableColumn colId2 = tablaListaRecepcionPedido.getColumn("Proveedor");
       
        
        ColCantidad.setMaxWidth(60);
        ColCantidad.setMinWidth(10);

        colDescripcion.setMaxWidth(620);
        colDescripcion.setMinWidth(50);
        
        colId2.setMaxWidth(140);
        colId2.setMinWidth(10);      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnCerrar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaListaRecepcionPedido = new javax.swing.JTable();
        btnCerrarPedido = new javax.swing.JButton();

        setBorder(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jLabel1.setText("Lista de productos");

        btnCerrar.setText("Cerrar");

        tablaListaRecepcionPedido.setModel(modeloTablaRecepcionPedido);
        jScrollPane1.setViewportView(tablaListaRecepcionPedido);

        btnCerrarPedido.setText("Cerrar pedido");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCerrarPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 709, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addGap(167, 167, 167)
                            .addComponent(btnCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(10, 10, 10))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnCerrar))
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 412, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnCerrarPedido)
                .addGap(0, 64, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnCerrar;
    public javax.swing.JButton btnCerrarPedido;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTable tablaListaRecepcionPedido;
    // End of variables declaration//GEN-END:variables
    public DefaultTableModel modeloTablaRecepcionPedido = new DefaultTableModel ();
}
